--Nitip Patching 12/12/22
---patching data profile --> DB CORE IP 10.204.178.100 

-- SELECT CIF WANT TO UPDATE IN USER_PROFILE 

SELECT CIF, USER_ID, IS_DELETED, UPDATED_BY, UPDATED_TIME  
FROM USER_PROFILE.USER_PROFILE  
WHERE CIF in ( 
'26000278825',
'26000278825'  
); 
  
-- SELECT DEVICE WANT TO UPDATE IN DEVICE_PROFILE 

SELECT DEVICE_ID, USER_ID, IS_DELETED, UPDATED_BY, UPDATED_TIME  
FROM USER_PROFILE.DEVICE_PROFILE  
WHERE DEVICE_ID in ( 
'7D37A6DF-65EA-4006-86D4-CABE8BF6B119'
); 

-- UPDATE IS_DELETED FROM USER_PROFILE TO BE TRUE 

UPDATE USER_PROFILE.USER_PROFILE 
SET IS_DELETED = 1, UPDATED_BY = 'PATCHED', UPDATED_TIME = sysdate 
WHERE CIF in ( 
'26000278825' 
); 

-- UPDATE IS_DELETED FROM DEVICE_PROFILE TO BE TRUE 

UPDATE USER_PROFILE.DEVICE_PROFILE  
SET IS_DELETED = 1, UPDATED_BY = 'PATCHED', UPDATED_TIME = sysdate 
WHERE DEVICE_ID in ( 
'7D37A6DF-65EA-4006-86D4-CABE8BF6B119'
);

=============================================================================================================================================

--Patching NTB --> COMPLEMENTARY  TO DB 10.204.238.55

select aa.ACCOUNT_NUMBER,  aa.IS_DELETED as application_delete, UR.IS_DELETED as user_registration_delete, aa.USER_CIF, aa.UPDATED_TIME,aa.HAS_MINIMUM_DEPOSIT, aa.UPDATED_BY , aa.BATCH_PROCESS 
from PROVISIONING.USER_REGISTRATION UR 
inner join PROVISIONING.ACCOUNT_APPLICATION aa 
on UR.USER_REGISTRATION_ID = aa.USER_REGISTRATION_ID
where aa.STATUS = 'CREATED'
AND aa.ACCOUNT_NUMBER is not NULL
AND aa.HAS_MINIMUM_DEPOSIT = '0' 
AND aa.IS_DELETED = '0'
--AND ur.IS_DELETED = '0'
and aa.USER_CIF in (
'9002321560' --SML-11266
);

update  PROVISIONING.ACCOUNT_APPLICATION SET  UPDATED_TIME = sysdate , updated_by = 'PATCHED'  where HAS_MINIMUM_DEPOSIT = 0 and IS_DELETED = 0 and account_number is not null and status='CREATED'
and USER_CIF in (
'9002321560' --SML-11266